CREATE TABLE shipments (
    id SERIAL PRIMARY KEY,
    customer_id UUID NOT NULL,
    tracking_number TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'requested',
    service_type TEXT NOT NULL DEFAULT 'standard',
    origin_address TEXT NOT NULL,
    destination_id INTEGER NOT NULL,
    total_weight DECIMAL(8,2),
    total_declared_value DECIMAL(10,2),
    pickup_scheduled_at TIMESTAMPTZ,
    processed_at TIMESTAMPTZ,
    shipped_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    carrier_name TEXT,
    carrier_tracking_number TEXT,
    customs_cleared_at TIMESTAMPTZ,
    estimated_delivery_date TIMESTAMPTZ,
    actual_delivery_date TIMESTAMPTZ,
    special_instructions TEXT,
    assigned_staff_id UUID,
    priority TEXT DEFAULT 'normal',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);