CREATE TABLE shipping_quotes (
    id SERIAL PRIMARY KEY,
    customer_id UUID,
    email TEXT,
    full_name TEXT,
    phone TEXT,
    destination_id INTEGER NOT NULL,
    weight_lbs DECIMAL(8,2) NOT NULL,
    length_inches DECIMAL(6,2),
    width_inches DECIMAL(6,2),
    height_inches DECIMAL(6,2),
    service_type TEXT DEFAULT 'standard',
    declared_value DECIMAL(10,2),
    base_shipping_cost DECIMAL(10,2) NOT NULL,
    consolidation_fee DECIMAL(8,2) DEFAULT 0,
    handling_fee DECIMAL(8,2) DEFAULT 0,
    insurance_cost DECIMAL(8,2) DEFAULT 0,
    total_cost DECIMAL(10,2) NOT NULL,
    estimated_transit_days INTEGER,
    special_instructions TEXT,
    status TEXT DEFAULT 'pending',
    quote_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);